/**
 * SecurityPreDetector — Lightweight pre-crawl protection detection.
 *
 * Pehle lightweight request se protection detect karein (headers + body-signature check):
 * - Cloudflare, SiteGround Anti-Bot, Sucuri, Wordfence, PerimeterX, DataDome
 * - Generic captcha/challenge pages
 *
 * Yeh detection pure request-level hai — koi heavy parsing nahi.
 * Result: { protected: boolean, provider: string|null, confidence: 'high'|'medium'|'low' }
 */

// ─── Known Protection Provider Patterns ───────────────────────────────

interface ProviderPattern {
  name: string;
  /** Header patterns to check (lowercase key: substring or regex in value) */
  headers: Array<{ key: string; pattern: RegExp | string }>;
  /** HTML body patterns */
  bodyPatterns: RegExp[];
  /** URL redirect patterns */
  urlPatterns: RegExp[];
  confidence: 'high' | 'medium' | 'low';
}

const PROVIDER_PATTERNS: ProviderPattern[] = [
  {
    name: 'Cloudflare',
    headers: [
      { key: 'server', pattern: /cloudflare/i },
      { key: 'cf-ray', pattern: /./ },
      { key: 'cf-challenge', pattern: /./ },
    ],
    bodyPatterns: [
      /cf-browser-verification/i,
      /__cf_challenge/i,
      /cloudflare-nginx/i,
      /checking your browser/i,
      /just a moment/i,
    ],
    urlPatterns: [
      /cloudflare/i,
      /cf-browser-verification/i,
    ],
    confidence: 'high',
  },
  {
    name: 'SiteGround',
    headers: [
      { key: 'x-sg-captcha', pattern: /./ },
    ],
    bodyPatterns: [
      /sgcaptcha/i,
      /proof-of-work/i,
      /siteground/i,
      /x-sg-captcha/i,
    ],
    urlPatterns: [
      /sgcaptcha/i,
      /\.well-known\/captcha/i,
    ],
    confidence: 'high',
  },
  {
    name: 'Sucuri',
    headers: [
      { key: 'x-sucuri-block', pattern: /./ },
      { key: 'x-sucuri-cache', pattern: /./ },
    ],
    bodyPatterns: [
      /sucuri/i,
      /cloudproxy/i,
      /access denied.*sucuri/i,
    ],
    urlPatterns: [],
    confidence: 'high',
  },
  {
    name: 'Wordfence',
    headers: [
      { key: 'x-wordfence', pattern: /./ },
    ],
    bodyPatterns: [
      /wordfence/i,
      /generated by wordfence/i,
      /blocked by wordfence/i,
    ],
    urlPatterns: [],
    confidence: 'high',
  },
  {
    name: 'PerimeterX / Human Security',
    headers: [
      { key: 'x-perimeterx', pattern: /./ },
      { key: 'x-px-block', pattern: /./ },
    ],
    bodyPatterns: [
      /perimeterx/i,
      /human security/i,
      /px-block/i,
      /_px/i,
    ],
    urlPatterns: [
      /_px/i,
      /perimeterx/i,
    ],
    confidence: 'high',
  },
  {
    name: 'DataDome',
    headers: [
      { key: 'x-datadome', pattern: /./ },
      { key: 'set-cookie', pattern: /datadome/i },
    ],
    bodyPatterns: [
      /datadome/i,
      /protected by datadome/i,
    ],
    urlPatterns: [],
    confidence: 'high',
  },
  {
    name: 'Akamai (Bot Manager)',
    headers: [
      { key: 'x-akamai-transformed', pattern: /./ },
      { key: 'x-akamai-request-id', pattern: /./ },
    ],
    bodyPatterns: [
      /akamai/i,
      /akamaiedge/i,
      /reference.*#[0-9a-f]{8,}/i,
    ],
    urlPatterns: [],
    confidence: 'medium',
  },
  {
    name: 'Generic Security',
    headers: [
      { key: 'x-blocked', pattern: /./ },
      { key: 'x-blocked-by', pattern: /./ },
    ],
    bodyPatterns: [
      /access denied/i,
      /blocked/i,
      /security check/i,
      /robot challenge/i,
      /attention required/i,
      /captcha/i,
      /g-recaptcha/i,
      /hcaptcha/i,
      /turnstile/i,
    ],
    urlPatterns: [
      /captcha/i,
      /challenge/i,
    ],
    confidence: 'medium',
  },
];

// ─── Types ────────────────────────────────────────────────────────────

export interface DetectionResult {
  protected: boolean;
  provider: string | null;
  confidence: 'high' | 'medium' | 'low' | 'none';
  /** How the detection was made: 'header' | 'body' | 'url' | 'status' | 'none' */
  detectionMethod: 'header' | 'body' | 'url' | 'status' | 'none';
  /** HTTP status code from the probe request */
  statusCode: number;
  /** Time taken for the probe in ms */
  probeTimeMs: number;
  /** Whether the probe succeeded */
  probeSucceeded: boolean;
  /** Human-readable detail about what was detected */
  detail: string | null;
}

// ─── Pre-Detector ────────────────────────────────────────────────────

export class SecurityPreDetector {
  private static readonly PROBE_TIMEOUT_MS = 15_000; // 15s max for probe
  private static readonly USER_AGENT =
    'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36';

  /**
   * Run a lightweight pre-detection probe against a URL.
   *
   * Sends a single HTTP GET request with a real Chrome UA and inspects:
   * 1. HTTP status code
   * 2. Response headers for known protection patterns
   * 3. Response body (first 50KB) for protection page signatures
   *
   * Returns a DetectionResult with provider info if protection is found.
   */
  async detect(url: string): Promise<DetectionResult> {
    const startTime = performance.now();

    try {
      const response = await fetch(url, {
        signal: AbortSignal.timeout(SecurityPreDetector.PROBE_TIMEOUT_MS),
        headers: {
          'User-Agent': SecurityPreDetector.USER_AGENT,
          Accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
          'Accept-Language': 'en-US,en;q=0.5',
        },
        redirect: 'follow',
      });

      const probeTimeMs = performance.now() - startTime;
      const statusCode = response.status;
      const finalUrl = response.url;

      // Read first 50KB of body for analysis
      const bodyChunk = await response.text();
      const bodySample = bodyChunk.slice(0, 50_000);

      // Normalize headers
      const headers: Record<string, string> = {};
      response.headers.forEach((value, key) => {
        headers[key.toLowerCase()] = value;
      });

      // ── Check status codes that indicate blocking ──────────────
      if (statusCode === 403) {
        // Check for provider patterns in headers first
        for (const provider of PROVIDER_PATTERNS) {
          for (const h of provider.headers) {
            const headerValue = headers[h.key];
            if (headerValue !== undefined) {
              if (h.pattern instanceof RegExp && h.pattern.test(headerValue)) {
                return this.makeResult(true, provider.name, provider.confidence, 'header', statusCode, probeTimeMs, true, `Header "${h.key}" matches ${provider.name}`);
              }
              if (typeof h.pattern === 'string' && headerValue.includes(h.pattern)) {
                return this.makeResult(true, provider.name, provider.confidence, 'header', statusCode, probeTimeMs, true, `Header "${h.key}" matches ${provider.name}`);
              }
            }
          }
        }
        // Generic 403 — flag as protected
        return this.makeResult(true, 'Generic Firewall', 'medium', 'status', statusCode, probeTimeMs, true, 'HTTP 403 Forbidden');
      }

      if (statusCode === 429) {
        return this.makeResult(true, 'Rate Limiter', 'high', 'status', statusCode, probeTimeMs, true, 'HTTP 429 Too Many Requests');
      }

      if (statusCode === 503) {
        // Check for provider patterns
        for (const provider of PROVIDER_PATTERNS) {
          if (provider.bodyPatterns.some(p => p.test(bodySample))) {
            return this.makeResult(true, provider.name, provider.confidence, 'body', statusCode, probeTimeMs, true, `Body matches ${provider.name} on 503`);
          }
        }
        return this.makeResult(true, 'Generic Protection', 'medium', 'status', statusCode, probeTimeMs, true, 'HTTP 503 Service Unavailable');
      }

      // ── Check final URL for challenge patterns ─────────────────
      for (const provider of PROVIDER_PATTERNS) {
        for (const urlPattern of provider.urlPatterns) {
          if (urlPattern.test(finalUrl)) {
            return this.makeResult(true, provider.name, provider.confidence, 'url', statusCode, probeTimeMs, true, `URL redirected to challenge page (${provider.name})`);
          }
        }
      }

      // ── Check headers for provider signatures ──────────────────
      for (const provider of PROVIDER_PATTERNS) {
        for (const h of provider.headers) {
          const headerValue = headers[h.key];
          if (headerValue !== undefined) {
            if (h.pattern instanceof RegExp && h.pattern.test(headerValue)) {
              return this.makeResult(true, provider.name, provider.confidence, 'header', statusCode, probeTimeMs, true, `Header "${h.key}" matches ${provider.name}`);
            }
            if (typeof h.pattern === 'string' && headerValue.includes(h.pattern)) {
              return this.makeResult(true, provider.name, provider.confidence, 'header', statusCode, probeTimeMs, true, `Header "${h.key}" matches ${provider.name}`);
            }
          }
        }
      }

      // ── Check body for provider signatures ────────────────────
      for (const provider of PROVIDER_PATTERNS) {
        for (const bodyPattern of provider.bodyPatterns) {
          if (bodyPattern.test(bodySample)) {
            return this.makeResult(true, provider.name, provider.confidence, 'body', statusCode, probeTimeMs, true, `Body matches ${provider.name} pattern`);
          }
        }
      }

      // ── Check for empty/tiny body (suspicious) ─────────────────
      if (bodySample.length < 200 && statusCode >= 200 && statusCode < 300) {
        return this.makeResult(true, 'Unknown Protection', 'low', 'body', statusCode, probeTimeMs, true, 'Response body is too small (< 200 bytes) — possible challenge page');
      }

      // ── No protection detected ─────────────────────────────────
      return this.makeResult(false, null, 'none', 'none', statusCode, probeTimeMs, true, null);

    } catch (err) {
      // Network error or timeout — probe failed
      const probeTimeMs = performance.now() - startTime;
      const errorMessage = err instanceof Error ? err.message : String(err);

      // Timeout is suspicious — might be a challenge page that hangs
      if (errorMessage.includes('timeout') || errorMessage.includes('Timeout') || errorMessage.includes('abort')) {
        return this.makeResult(true, 'Unknown Protection', 'low', 'none', 0, probeTimeMs, false, 'Probe timed out — possible challenge page or firewall');
      }

      // DNS / connection error — site may be down or blocking
      return this.makeResult(false, null, 'none', 'none', 0, probeTimeMs, false, `Probe failed: ${errorMessage}`);
    }
  }

  private makeResult(
    protected_: boolean,
    provider: string | null,
    confidence: DetectionResult['confidence'],
    detectionMethod: DetectionResult['detectionMethod'],
    statusCode: number,
    probeTimeMs: number,
    probeSucceeded: boolean,
    detail: string | null,
  ): DetectionResult {
    return {
      protected: protected_,
      provider,
      confidence,
      detectionMethod,
      statusCode,
      probeTimeMs: Math.round(probeTimeMs),
      probeSucceeded,
      detail,
    };
  }
}

export default SecurityPreDetector;
